package view;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import java.sql.*;
import config.KoneksiDb;
import java.awt.HeadlessException;

public class loginRegisterPage extends javax.swing.JFrame {

    Connection conn;
    Statement stm;
    ResultSet rs;
    
    public loginRegisterPage() {
        initComponents();
        setLocationRelativeTo(null);
        
        KoneksiDb koneksi = new KoneksiDb();
        koneksi.Config();
        conn = koneksi.conn;
        stm = koneksi.stm;
    }
    
    private void setView(JPanel panel, JPanel view) {
        panel.removeAll();
        panel.repaint();
        panel.revalidate();
        
        panel.add(view);
        panel.repaint();
        panel.revalidate();
    }
    
    private void formResetRegister(){
        usernameTextFieldRegister.setText("");
        jPasswordFieldRegister.setText("");
        jPasswordFieldRepeatRegister.setText("");
    }
    
    // Method to hash the password using MD5
    public String hashPasswordMD5(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : messageDigest) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterAndLoginPage = new javax.swing.JPanel();
        JudulLoginRegister = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MainPage = new javax.swing.JPanel();
        RegisterPage = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        usernameTextFieldRegister = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonBatal = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPasswordFieldRegister = new javax.swing.JPasswordField();
        jPasswordFieldRepeatRegister = new javax.swing.JPasswordField();
        LoginPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextUsernameLogin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPasswordFieldLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        RegisterAndLoginPage.setBackground(new java.awt.Color(255, 255, 255));

        JudulLoginRegister.setBackground(new java.awt.Color(70, 133, 133));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JudulLoginRegisterLayout = new javax.swing.GroupLayout(JudulLoginRegister);
        JudulLoginRegister.setLayout(JudulLoginRegisterLayout);
        JudulLoginRegisterLayout.setHorizontalGroup(
            JudulLoginRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JudulLoginRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        JudulLoginRegisterLayout.setVerticalGroup(
            JudulLoginRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JudulLoginRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JudulLoginRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPage.setBackground(new java.awt.Color(255, 255, 255));
        MainPage.setLayout(new java.awt.CardLayout());

        RegisterPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 133, 133));
        jLabel7.setText("Register Page");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 133, 133));
        jLabel8.setText("Hi, Welcome to Loundry App!");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(70, 133, 133));
        jLabel11.setText("Username");

        usernameTextFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usernameTextFieldRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(70, 133, 133));
        jLabel12.setText("Password");

        jButtonSubmit.setBackground(new java.awt.Color(70, 133, 133));
        jButtonSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("submit");
        jButtonSubmit.setAlignmentY(0.0F);
        jButtonSubmit.setBorder(null);
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(156, 219, 166));
        jLabel15.setText("klik disini");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(70, 133, 133));
        jLabel16.setText("Jika kamu memiliki akun,");

        jButtonBatal.setBackground(new java.awt.Color(255, 0, 0));
        jButtonBatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBatal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBatal.setText("Batal");
        jButtonBatal.setAlignmentY(0.0F);
        jButtonBatal.setBorder(null);
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(70, 133, 133));
        jLabel17.setText("Repeat Password");

        jPasswordFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPasswordFieldRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jPasswordFieldRepeatRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPasswordFieldRepeatRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        javax.swing.GroupLayout RegisterPageLayout = new javax.swing.GroupLayout(RegisterPage);
        RegisterPage.setLayout(RegisterPageLayout);
        RegisterPageLayout.setHorizontalGroup(
            RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameTextFieldRegister)
                    .addGroup(RegisterPageLayout.createSequentialGroup()
                        .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterPageLayout.createSequentialGroup()
                        .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(RegisterPageLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPasswordFieldRegister)
                    .addComponent(jPasswordFieldRepeatRegister))
                .addContainerGap())
        );
        RegisterPageLayout.setVerticalGroup(
            RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldRepeatRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        MainPage.add(RegisterPage, "card3");

        LoginPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 133, 133));
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 133, 133));
        jLabel2.setText("Hi, Welcome to Loundry App!");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 133, 133));
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 133, 133));
        jLabel4.setText("Password");

        jButton1.setBackground(new java.awt.Color(70, 133, 133));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("submit");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextUsernameLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextUsernameLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(70, 133, 133));
        jLabel13.setText("Jika kamu tidak memiliki akun,");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(156, 219, 166));
        jLabel14.setText("klik disini");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jPasswordFieldLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPasswordFieldLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        javax.swing.GroupLayout LoginPageLayout = new javax.swing.GroupLayout(LoginPage);
        LoginPage.setLayout(LoginPageLayout);
        LoginPageLayout.setHorizontalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LoginPageLayout.createSequentialGroup()
                        .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(LoginPageLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addGap(0, 323, Short.MAX_VALUE))
                    .addComponent(jPasswordFieldLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextUsernameLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
                .addContainerGap())
        );
        LoginPageLayout.setVerticalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        MainPage.add(LoginPage, "card2");

        javax.swing.GroupLayout RegisterAndLoginPageLayout = new javax.swing.GroupLayout(RegisterAndLoginPage);
        RegisterAndLoginPage.setLayout(RegisterAndLoginPageLayout);
        RegisterAndLoginPageLayout.setHorizontalGroup(
            RegisterAndLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterAndLoginPageLayout.createSequentialGroup()
                .addComponent(JudulLoginRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisterAndLoginPageLayout.setVerticalGroup(
            RegisterAndLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JudulLoginRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterAndLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterAndLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = jTextUsernameLogin.getText();
        String password = new String (jPasswordFieldLogin.getPassword());
        String passwordHash = hashPasswordMD5(password);
        
        try {
            
            if (username.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(this, "form inputan tidak boleh kosong", "pesan", JOptionPane.ERROR_MESSAGE);
            } else {
                // password hash
                
                String sql              = "select * from tabel_user where username = ? and password = ? ";
                PreparedStatement pst   = conn.prepareStatement(sql);
                pst.setString(1, username);
                pst.setString(2, passwordHash);
                
                ResultSet res = pst.executeQuery();
                if (res.next()) {
                    
                    // apabila berhasil login                 
                    JOptionPane.showMessageDialog(this, "login berhasil", "pesan", JOptionPane.INFORMATION_MESSAGE);
                    mainUtama main = new mainUtama();
                    main.setVisible(true);
                    
                } else {
                    
                    JOptionPane.showMessageDialog(this, "username atau password salah", "pesan", JOptionPane.ERROR_MESSAGE);
                            
                }
                
            }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan Sql atau Kesalahan lain", "pesan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.out.println("CLose button Clicked");
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.out.println("Minimize button Clicked");
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        String passwordRegister         = jPasswordFieldRegister.getText();
        String repeatPasswordRegister   = jPasswordFieldRepeatRegister.getText();
        String usernameRegister         = usernameTextFieldRegister.getText();
        try {
            
            if (passwordRegister.equals("") || repeatPasswordRegister.equals("") || usernameRegister.equals("")) {
                
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "pesan" , JOptionPane.ERROR_MESSAGE);
                
            } else if (!passwordRegister.equals(repeatPasswordRegister)){
                
                JOptionPane.showMessageDialog(this, "Password harus sama", "pesan", JOptionPane.ERROR_MESSAGE);
                
            } else {
                
                String hashPasswordMd5  = hashPasswordMD5(passwordRegister);
                
                String query            = "insert into tabel_user (username, password) values (?, ?)";
                PreparedStatement pst   = conn.prepareStatement(query);
                pst.setString(1, usernameRegister);
                pst.setString(2, hashPasswordMd5);
                
                int affectedRows = pst.executeUpdate();
                if (affectedRows > 0) {
                    JOptionPane.showMessageDialog(this, "Register sudah berhasil silahkan anda login", "pesan", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "terjadi kesalahan SQL dan Kesalahan lain", "pesan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        setView(MainPage, RegisterPage);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        setView(MainPage, LoginPage);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        formResetRegister();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginRegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginRegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginRegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginRegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginRegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JudulLoginRegister;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JPanel MainPage;
    private javax.swing.JPanel RegisterAndLoginPage;
    private javax.swing.JPanel RegisterPage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    private javax.swing.JPasswordField jPasswordFieldRegister;
    private javax.swing.JPasswordField jPasswordFieldRepeatRegister;
    private javax.swing.JTextField jTextUsernameLogin;
    private javax.swing.JTextField usernameTextFieldRegister;
    // End of variables declaration//GEN-END:variables
}
