package view;

import config.KoneksiDb;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class mainUtama extends JFrame {

    Connection conn;
    Statement stm;
    ResultSet rs;
    
    public mainUtama() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Dashboard");
        
        KoneksiDb koneksi = new KoneksiDb();
        koneksi.Config();
        conn = KoneksiDb.conn;
        stm = KoneksiDb.stm;
        
        // get Data Customer
        getDataCustomer();
        
        //get Data Order
        getDataOrder();
        reset();
    }
    
    private void setView(JPanel panel, JPanel view) {
        panel.removeAll();
        panel.repaint();
        panel.revalidate();
        
        panel.add(view);
        panel.repaint();
        panel.revalidate();
    }
    
    // Customer    
    
    private void getDataCustomer(){
        DefaultTableModel model     = (DefaultTableModel) CustomerTable.getModel();
        // Menghapus semua baris yang ada di model
        model.setRowCount(0);

        // Menambahkan kolom hanya jika belum ada
        if (model.getColumnCount() == 0) {
            model.addColumn("No");
            model.addColumn("Kode Kostumer");
            model.addColumn("Nama");
            model.addColumn("No Telp");
            model.addColumn("Alamat");
        }
        try {
            int no = 1;
            String sql                  = "select * from `tabel_custumer` ";
            stm                         = conn.createStatement();
            ResultSet res               = stm.executeQuery(sql);
            
            // Menampilkan data dari database           
            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4)}
                
                );
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "pesan", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    // order
    private void getDataOrder(){
       DefaultTableModel model     = (DefaultTableModel) orderTabel.getModel();
        // Menghapus semua baris yang ada di model
        model.setRowCount(0);

        // Menambahkan kolom hanya jika belum ada
        if (model.getColumnCount() == 0) {
            model.addColumn("No");
            model.addColumn("Kode Order");
            model.addColumn("Tanggal");
            model.addColumn("Keterangan");
            model.addColumn("Status");
            model.addColumn("Berat Barang");
            model.addColumn("Harga");
            model.addColumn("Total");
        }
        try {
            int no = 1;
            String sql                  = "select * from `order` ";
            PreparedStatement pst       = conn.prepareStatement(sql);
            ResultSet res               = pst.executeQuery();
            
            // Menampilkan data dari database           
            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7)
                    }
                );
            }
            
            pst.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "pesan", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    
    private void reset(){
        jTextFieldCustomer.setText("");
        jTextFieldNoTelp.setText("");
        jTextAreaAlamat.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MainContent = new javax.swing.JPanel();
        DataCustomer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCustomer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cariDataCostumer = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        simpanCustomer = new javax.swing.JLabel();
        updateCustomer = new javax.swing.JLabel();
        deleteCustomer = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldNoTelp = new javax.swing.JTextField();
        jTextFieldIdCustomer = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        cariCostumer = new javax.swing.JButton();
        Order = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderTabel = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jDateChooserTanggal = new com.toedter.calendar.JDateChooser();
        cs1 = new javax.swing.JLabel();
        jTextFieldIdCustomer1 = new javax.swing.JTextField();
        Pengambilan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Content.setBackground(new java.awt.Color(255, 255, 255));

        Navbar.setBackground(new java.awt.Color(70, 133, 133));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 249, 196));
        jLabel1.setText("Data Customer");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 249, 196));
        jLabel3.setText("Order");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(222, 249, 196));
        jLabel4.setText("Pengambilan");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavbarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(NavbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainContent.setBackground(new java.awt.Color(255, 255, 255));
        MainContent.setLayout(new java.awt.CardLayout());

        DataCustomer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 133, 133));
        jLabel2.setText("DATA CUSTOMER");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(70, 133, 133));
        jLabel11.setText("Nama       : ");

        jTextFieldCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(70, 133, 133));
        jLabel12.setText("No. Tlp    :");

        cariDataCostumer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cariDataCostumer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));
        cariDataCostumer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariDataCostumerKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(70, 133, 133));
        jLabel14.setText("Alamat             : ");

        jTextAreaAlamat.setColumns(20);
        jTextAreaAlamat.setRows(5);
        jTextAreaAlamat.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));
        jScrollPane1.setViewportView(jTextAreaAlamat);

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CustomerTable);

        simpanCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        simpanCustomer.setForeground(new java.awt.Color(70, 133, 133));
        simpanCustomer.setText("Save");
        simpanCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanCustomerMouseClicked(evt);
            }
        });

        updateCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateCustomer.setForeground(new java.awt.Color(70, 133, 133));
        updateCustomer.setText("Update");
        updateCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateCustomerMouseClicked(evt);
            }
        });

        deleteCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteCustomer.setForeground(new java.awt.Color(70, 133, 133));
        deleteCustomer.setText("Delete");
        deleteCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCustomerMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(70, 133, 133));
        jLabel18.setText("Reset");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jTextFieldNoTelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNoTelp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jTextFieldIdCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldIdCustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(70, 133, 133));
        jLabel13.setText("ID       : ");

        cs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cs.setForeground(new java.awt.Color(70, 133, 133));
        cs.setText("CS");

        cariCostumer.setText("Cari");
        cariCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariCostumerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataCustomerLayout = new javax.swing.GroupLayout(DataCustomer);
        DataCustomer.setLayout(DataCustomerLayout);
        DataCustomerLayout.setHorizontalGroup(
            DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataCustomerLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(DataCustomerLayout.createSequentialGroup()
                            .addComponent(cariCostumer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cariDataCostumer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataCustomerLayout.createSequentialGroup()
                        .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DataCustomerLayout.createSequentialGroup()
                                .addComponent(simpanCustomer)
                                .addGap(57, 57, 57)
                                .addComponent(updateCustomer)
                                .addGap(51, 51, 51)
                                .addComponent(deleteCustomer)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel18))
                            .addGroup(DataCustomerLayout.createSequentialGroup()
                                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DataCustomerLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataCustomerLayout.createSequentialGroup()
                                        .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataCustomerLayout.createSequentialGroup()
                                        .addComponent(cs)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldIdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(324, 324, 324))
        );
        DataCustomerLayout.setVerticalGroup(
            DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataCustomerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cs))
                .addGap(18, 18, 18)
                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataCustomerLayout.createSequentialGroup()
                        .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpanCustomer)
                            .addComponent(updateCustomer)
                            .addComponent(deleteCustomer)
                            .addComponent(jLabel18))
                        .addGap(24, 24, 24)
                        .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cariDataCostumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariCostumer))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)))
        );

        MainContent.add(DataCustomer, "card2");

        Order.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 133, 133));
        jLabel8.setText("ORDER");

        orderTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        orderTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTabelMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(orderTabel);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(70, 133, 133));
        jLabel20.setText("Kode Order   : ");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(70, 133, 133));
        jLabel21.setText("Tanggal         : ");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(70, 133, 133));
        jLabel22.setText("Keterangan   : ");

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(70, 133, 133));
        jLabel23.setText("Berat barang : ");

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(70, 133, 133));
        jLabel24.setText("Harga       : ");

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(70, 133, 133));
        jLabel25.setText("Status       :");

        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(70, 133, 133));
        jLabel26.setText("Total        : ");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(70, 133, 133));
        jLabel27.setText("Save");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(70, 133, 133));
        jLabel28.setText("Update");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(70, 133, 133));
        jLabel29.setText("Delete");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(70, 133, 133));
        jLabel30.setText("Reset");

        jTextField17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField17.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(70, 133, 133));
        jLabel38.setText("Cari :");

        jTextField13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        cs1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cs1.setForeground(new java.awt.Color(70, 133, 133));
        cs1.setText("OR");

        jTextFieldIdCustomer1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldIdCustomer1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(OrderLayout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel28))
                                    .addGroup(OrderLayout.createSequentialGroup()
                                        .addGap(208, 208, 208)
                                        .addComponent(jLabel29)))
                                .addGap(44, 44, 44)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(OrderLayout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(jDateChooserTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(OrderLayout.createSequentialGroup()
                                        .addComponent(cs1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldIdCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldIdCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cs1)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel23))
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jDateChooserTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        MainContent.add(Order, "card3");

        Pengambilan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 133, 133));
        jLabel9.setText("PENGAMBILAN");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(70, 133, 133));
        jLabel31.setText("Nama Pengambil         :");

        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField14.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(70, 133, 133));
        jLabel32.setText("Tanggal Pengambilan : ");

        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField15.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(70, 133, 133));
        jLabel33.setText("Kode Order                  : ");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(70, 133, 133));
        jLabel34.setText("Save");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(70, 133, 133));
        jLabel35.setText("Update");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(70, 133, 133));
        jLabel36.setText("Delete");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(70, 133, 133));
        jLabel37.setText("Reset");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(70, 133, 133));
        jLabel39.setText("Cari :");

        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField16.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(70, 133, 133), new java.awt.Color(70, 133, 133)));

        javax.swing.GroupLayout PengambilanLayout = new javax.swing.GroupLayout(Pengambilan);
        Pengambilan.setLayout(PengambilanLayout);
        PengambilanLayout.setHorizontalGroup(
            PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengambilanLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PengambilanLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(339, 339, 339))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PengambilanLayout.createSequentialGroup()
                        .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PengambilanLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PengambilanLayout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel35)
                                    .addGap(37, 37, 37)
                                    .addComponent(jLabel36)
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel37))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PengambilanLayout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PengambilanLayout.createSequentialGroup()
                                        .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(84, 84, 84))))
        );
        PengambilanLayout.setVerticalGroup(
            PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengambilanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(PengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        MainContent.add(Pengambilan, "card4");

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.out.println("CLose button Clicked");
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.out.println("Minimize button Clicked");
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setView(MainContent, DataCustomer);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        setView(MainContent, Order);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        setView(MainContent, Pengambilan);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void simpanCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanCustomerMouseClicked
        // sudah beres simpan data costumer        
        
        String nama          = jTextFieldCustomer.getText();
        String noTelp        = jTextFieldNoTelp.getText();
        String alamat        = jTextAreaAlamat.getText();
        String kodeCustomer  = jTextFieldIdCustomer.getText();

        try {
            if (nama.equals("") || noTelp.equals("") || alamat.equals("")) {
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "pesan", JOptionPane.ERROR_MESSAGE);
            } else {
                String query = "INSERT INTO tabel_custumer (kode_customer, nama, no_telp, alamat) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pst = conn.prepareStatement(query)) {
                    pst.setString(1, "CS" + kodeCustomer);
                    pst.setString(2, nama);
                    pst.setString(3, noTelp);
                    pst.setString(4, alamat);
                    pst.executeUpdate();
                    System.out.println(pst);
                    JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "pesan", JOptionPane.INFORMATION_MESSAGE);
                    getDataCustomer();
                    reset();
                    stm.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan SQL: " + e.getMessage(), "pesan", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "pesan", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_simpanCustomerMouseClicked

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        // menampilkan data kedalam form pengisian:
        int baris       = CustomerTable.rowAtPoint(evt.getPoint());
        cs.setVisible(false);
        
        String idCustomer     = CustomerTable.getValueAt(baris,1).toString();
        jTextFieldIdCustomer.setText(idCustomer);
        jTextFieldIdCustomer.setEnabled(false);
        
        String nama     = CustomerTable.getValueAt(baris,2).toString();
        jTextFieldCustomer.setText(nama);
        
        String noTelp   = CustomerTable.getValueAt(baris,3).toString();
        jTextFieldNoTelp.setText(noTelp);
        
        String alamat   = CustomerTable.getValueAt(baris,4).toString();
        jTextAreaAlamat.setText(alamat);
        
        
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void updateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCustomerMouseClicked
        // sudah beres di edit costumernya
        
        String nama = jTextFieldCustomer.getText();
        String noTelp = jTextFieldNoTelp.getText();
        String alamat = jTextAreaAlamat.getText();
        String idCustomer = jTextFieldIdCustomer.getText();

        try {
            if (nama.equals("") || noTelp.equals("") || alamat.equals("")) {
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "pesan", JOptionPane.ERROR_MESSAGE);
            } else {
                String query = "UPDATE tabel_custumer SET nama = ?, no_telp = ?, alamat = ? WHERE kode_customer = ?";
                try (PreparedStatement pst = conn.prepareStatement(query)) {
                    pst.setString(1, nama);
                    pst.setString(2, noTelp);
                    pst.setString(3, alamat);
                    pst.setString(4, idCustomer);
                    pst.executeUpdate();
                    System.out.println(pst);
                    JOptionPane.showMessageDialog(this, "Data berhasil diedit", "pesan", JOptionPane.INFORMATION_MESSAGE);
                    getDataCustomer();
                    reset();
                    stm.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan SQL: " + e.getMessage(), "pesan", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "pesan", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_updateCustomerMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        reset();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void deleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerMouseClicked
        String idCostumer = jTextFieldIdCustomer.getText();
        try {
            String query            = "delete from tabel_custumer where kode_customer = ?";
            PreparedStatement pst   = conn.prepareStatement(query);
            pst.setString(1, idCostumer);
            pst.executeUpdate();
            System.out.println(pst);
            JOptionPane.showMessageDialog(this, "berhasil dihapus");
            stm.close();
            getDataCustomer();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "terjadi kesalahan" + e.getMessage());
        }
    }//GEN-LAST:event_deleteCustomerMouseClicked

    private void cariDataCostumerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariDataCostumerKeyReleased
        
        
    }//GEN-LAST:event_cariDataCostumerKeyReleased

    private void cariCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariCostumerActionPerformed
        String cariCostumer                   = cariDataCostumer.getText();
        DefaultTableModel model               = (DefaultTableModel) CustomerTable.getModel();
        model.getDataVector().removeAllElements();
        try {
            
            String sql                        = "SELECT * from tabel_custumer where kode_customer = ?";
                PreparedStatement pst = conn.prepareStatement(sql, 
                        ResultSet.TYPE_SCROLL_INSENSITIVE, 
                        ResultSet.CONCUR_READ_ONLY);
                
                pst.setString(1, cariCostumer);
                rs = pst.executeQuery();
                rs.last();
                int rowCount = rs.getRow();
                rs.beforeFirst();
                int nomor = 1;
                if (rowCount > 0) {
                    while (rs.next()) {                    
                        String kodeCustomer        = rs.getString("kode_customer");
                        String nama                = rs.getString("nama");
                        String noTelp              = rs.getString("no_telp");
                        String alamat              = rs.getString("alamat");
                        
                        Object[] data = {nomor, kodeCustomer, nama, noTelp, alamat };
                        model.addRow(data);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
                }
            rs.close();
            pst.close();
        } catch (SQLException e) {
            System.out.println("terdapat query yang salah " + e.getMessage());
        }
    }//GEN-LAST:event_cariCostumerActionPerformed

    private void orderTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTabelMouseClicked
        
    }//GEN-LAST:event_orderTabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JPanel DataCustomer;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel Order;
    private javax.swing.JPanel Pengambilan;
    private javax.swing.JButton cariCostumer;
    private javax.swing.JTextField cariDataCostumer;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel cs1;
    private javax.swing.JLabel deleteCustomer;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooserTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextAreaAlamat;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldCustomer;
    private javax.swing.JTextField jTextFieldIdCustomer;
    private javax.swing.JTextField jTextFieldIdCustomer1;
    private javax.swing.JTextField jTextFieldNoTelp;
    private javax.swing.JTable orderTabel;
    private javax.swing.JLabel simpanCustomer;
    private javax.swing.JLabel updateCustomer;
    // End of variables declaration//GEN-END:variables

}
